services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: pycap-backend
    environment:
      WORKSPACE_ROOT: /workspace
    volumes:
    - .:/workspace
    ports:
    - 8877:8000
    networks:
    - shared-net
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: pycap-frontend
    depends_on:
    - backend
    ports:
    - 8878:80
    networks:
    - shared-net
networks:
  shared-net:
    external: true
